baseURL: ""
languageCode: "en-us"
title: "Docs"
disableKinds: ["taxonomy", "taxonomyTerm", "section", "RSS"]
sectionPagesMenu: "main"
defaultContentLanguage: "en"
params:
  env: "dev"
  latest: 1.3.2
  version: 1.3.x
  versions:
    - 1.3.x
    - 0.5.x

markup:
  goldmark:
    renderer:
      unsafe: true

languages:
  en:
    languageName: "English"
    weight: 1
