baseURL: ""
languageCode: "en-us"
title: "Docs"
disableKinds: ["taxonomy", "taxonomyTerm", "section", "RSS"]
sectionPagesMenu: "main"
defaultContentLanguage: "en"
params:
  env: "dev"
  latest: 2.0.x
  version: 1.3.x
  versions:
    - 2.0.x
    - 1.3.x

markup:
  goldmark:
    renderer:
      unsafe: true

languages:
  en:
    languageName: "English"
    weight: 1
