baseURL: ""
languageCode: "en-us"
title: "Docs"
disableKinds: ["taxonomy", "taxonomyTerm", "section", "RSS"]
sectionPagesMenu: "main"
defaultContentLanguage: "en"
params:
  env: "dev"
  version: 1.3.2

markup:
  goldmark:
    renderer:
      unsafe: true

languages:
  en:
    languageName: "English"
    weight: 1
