---
name: deploy

on:
  push:
    branch:
      - 'v-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - id: axentix-version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: axentix/axentix

      - name: Get destination directory
        id: dest-dir
        run: |
          BRANCH=${GITHUB_REF##*/}
          echo ::set-output name=DIR::${BRANCH:2}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.87.0'
          extended: true

      - name: Build
        run: hugo --minify --baseURL https://axentix.github.io/docs/${{ steps.dest-dir.outputs.DIR }}
        env:
          AX_ENV: production
          AX_LATEST_VERSION: ${{ steps.axentix-version.outputs.release }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ${{ steps.dest-dir.outputs.DIR }}
