---
name: deploy

on:
  push:
    branch:
      - 'v-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Get latest axentix version
        id: axentix-version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: axentix/axentix

      - name: Get destination directory
        id: dest-dir
        run: |
          BRANCH=${GITHUB_REF##*/}
          echo ::set-output name=DIR::${BRANCH:2}

      - name: Get default branch
        run: |
          DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
          echo "default_branch_ref=refs/heads/$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.87.0'
          extended: true

      - name: Build main docs
        if: ${{ env.default_branch_ref == github.ref }}
        run: hugo --minify --baseURL https://axentix.github.io/docs
        env:
          AX_ENV: production
          AX_LATEST_VERSION: ${{ steps.axentix-version.outputs.release }}

      - name: Build docs
        if: ${{ env.default_branch_ref != github.ref }}
        run: hugo --minify --baseURL https://axentix.github.io/docs/${{ steps.dest-dir.outputs.DIR }}
        env:
          AX_ENV: production
          AX_LATEST_VERSION: ${{ steps.axentix-version.outputs.release }}

      - name: Get versions
        id: versions
        run: |
          BRANCHES=( $(git branch -r --list origin/v-* | tr '*' ' ' | tr 'origin/v-' ' ') )
          VERSIONS=$(printf ",%s" "${BRANCHES[@]}")
          echo ${BRANCHES}
          echo ${VERSIONS:1}
          echo ::set-output name=VERSIONS::${VERSIONS:1}

      - name: Deploy main docs
        if: ${{ env.default_branch_ref == github.ref }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./public
          clean-exclude: ${{ steps.versions.outputs.VERSIONS }}

      - name: Deploy docs
        if: ${{ env.default_branch_ref != github.ref }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./public
          target-folder: ${{ steps.dest-dir.outputs.DIR }}
